OUTPUT_DIR: 'results/'

INPUT:
  SIZE: (256, 256)
  CROP_SIZE: (224, 224)
  SOURCE_TRANSFORMS: ('random_flip', 'random_resized_crop', 'normalize', 'colorjitter')
  TARGET_TRANSFORMS: ('random_flip', 'random_resized_crop', 'normalize')
  TEST_TRANSFORMS: ('center_crop', 'normalize')
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATASET:
  ROOT: '../data/list/'
  NAME: 'miniDomainNet'
  SOURCE_DOMAINS: ['clipart', 'painting', 'real', 'sketch']
  TARGET_DOMAINS: ['clipart', 'painting', 'real', 'sketch']
  NUM_CLASS: 126

DATALOADER:
  SOURCE:
    BATCH_SIZE: 32 #  32
  TARGET:
    BATCH_SIZE: 32 # 32
  TEST:
    BATCH_SIZE: 32 # 32

TRAIN:
  PRINT_FREQ: 200
  TEST_FREQ: 2
OPTIM:
#  NAME: 'Adam'
#  LR: 0.00001
  NAME: 'SGD'
  LR: 0.001

TRAINER:
  NAME: 'Detective'
  MAX_EPOCHS: 50
#  MAX_EPOCHS: 20
  BETA: 1.0
  LAMBDA: 0.05
#  ACTIVE_ROUND: [6, 8, 10, 12, 14]
  CLIP_GRAD_NORM: 15.0

NETWORK:
  Z_DIM: 512
  FROZEN: False
SEED: 0
GPU_ID: 4
